Feature/server connection processing
OSTOLEX-Technologies/castledice-game-client pull request #51
Opened 2024-03-31 16:25 UTC by Mehanari

Added logic for server connection process and visuals to represent it.

2024-04-10 23:04 UTC, GGLinker requested changes

2024-04-10 23:04 UTC, GGLinker commented on Assets/Src/Components/TextSwitchingAnimation.cs
> +       private void Update()
Do we rly need timer implementation via Update()? It'll be ticking besides of the fact whether parent GameObject is active or not. We'll need to Destroy() parent GO to force stop such an update. I'd prefer to refactor this with usage of async awaits chain or some kind of Coroutine

2024-04-10 23:04 UTC, GGLinker commented on Assets/Src/General/FloatValueConfig.cs
> +namespace Src.General
Seems a _lot_ overcomplicated to me. Mb this should be a simple SF in a corresponding classes, or if such a config class has been created for low-range purpose bunch of another classes, it'd be better to move such a SF into those parent interfaces' declarations?

2024-04-10 23:04 UTC, GGLinker commented on Assets/Src/General/StringsListConfig.cs
> +    public class StringsListConfig : ScriptableObject
More understandable move with such a config, but still it's too low-level structure to extract while we have such a powerful tool as SerializeField attribute

2024-04-10 23:04 UTC, GGLinker commented on Assets/Src/NetworkingModule/ClientWrapper.cs
> +        public event EventHandler<ConnectionFailedEventArgs> ConnectionFailed;
If this class would be used not only within some non-large family of classes / namespace, mb it'd be better to make these events of **Action** type?

2024-04-10 23:04 UTC, GGLinker commented on Assets/Src/NetworkingModule/ClientWrapper.cs
> +            ConnectionFailed?.Invoke(this, e);
Despite of the fact that EventHandler is stated in C# standard as recommended solution, such meaningless mentions of <_this, e_> looks a bit weird

2024-04-10 23:04 UTC, GGLinker commented on Assets/Src/NetworkingModule/IClientWrapper.cs
> +            Message message = null);
I think it's not a good idea to make default method parameter values in interface bc it feels like side effect. And besides of that, such a magic numbers organically mix up into smth like config which we use anywhere we can. Why not there too?

2024-04-10 23:04 UTC, GGLinker commented on Assets/Src/GameplayPresenter/ServerConnection/ServerConnectionPresenter.cs
> +            var maxConnectionAttempts = _connectionConfig.MaxConnectionAttempts;
In IMessageSender (and in IClientWrapper) we use method parameter to get max connection attempts count. I think we should apply such a solution there too.

2024-04-11 11:16 UTC, Mehanari commented on Assets/Src/Components/TextSwitchingAnimation.cs
> +       private void Update()
Update automatically stops if parent game object is deactivated.

2024-04-11 16:38 UTC, GGLinker approved these changes

2024-04-11 16:49 UTC, merged